### PR TITLE
Add license notices to source files, etc.

### PR DESCRIPTION
**Pull request by giang-nghg**
This pull request just makes the open source licensing clearer and makes some very minor documentation tweaks:

Add license header comments to source code files.
Rename readme.md to README.md because the latter seems to be the de facto standard now
Update README.md to say that ResponseBot is open source.
Add license header comments to documentation source files too.
Add a one-line summary of ResponseBot to the documentation index page.

### CODE REVIEW

**Comment by giang-nghg** [comment]
@kfogel Hi, we re-created this pull request. Please let us know if we missed anything, thanks!

**Comment by kfogel** [comment]
Hi, @giang271291 .  I also resubmitted, in #6.  Thanks for recreating, but I think for attribution purposes it's better to merge #6; it should be the same changes (though I haven't checked over this one, since I was making #6 anyway).

**Comment by cpdbop** [comment]
Thanks @kfogel , merged your PR

**Comment by kfogel** [comment]
Thanks!

**Pull request closed without merging**
